// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXIMltjmz4kvhl10FrUngBFZv8Rpsnvoo',
    appId: '1:381479615208:web:09f50f2f58e090fb07275d',
    messagingSenderId: '381479615208',
    projectId: 'class-attendance-8e791',
    authDomain: 'class-attendance-8e791.firebaseapp.com',
    storageBucket: 'class-attendance-8e791.firebasestorage.app',
    measurementId: 'G-LHVZ979R1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3nWLGUzzlcjQ6bEjqutgRpHgeJKk2wVQ',
    appId: '1:381479615208:android:03439acf5c4865e907275d',
    messagingSenderId: '381479615208',
    projectId: 'class-attendance-8e791',
    storageBucket: 'class-attendance-8e791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZxXlauC5J1WUq20bcp59GwYWJMIvUnQ',
    appId: '1:381479615208:ios:b2cf6295ad45f05207275d',
    messagingSenderId: '381479615208',
    projectId: 'class-attendance-8e791',
    storageBucket: 'class-attendance-8e791.firebasestorage.app',
    iosBundleId: 'com.app.class.attendance',
  );
}
